name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm ci

      - name: Build package
        run: pnpm run build

      - name: Publish package
        run: pnpm publish --no-git-checks
